#!/bin/sh
#
# Start the wifi....
#

case "$1" in
  start)
	printf "Starting wifi: "
	modprobe brcmfmac
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping wifi: "
	modprobe -r brcmfmac
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

