#!/bin/sh
#
# Start the wpa_supplicant....
#

case "$1" in
  start)
	printf "Starting wpa_supplicant: "
	wpa_supplicant -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf -B
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping wpa_supplicant: "
	killall wpa_supplicant
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

