#!/bin/sh
#
# Start the udhcpc....
#

case "$1" in
  start)
	printf "Starting udhcpc: "
	udhcpc -iwlan0 &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping udhcpc: "
	killall udhcpc
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

