#!/bin/sh
#
# Start the fish-guard....
#

case "$1" in
  start)
	printf "Starting fish-guard: "
	mkdir -p /boot
	mount /dev/mmcblk0p1 /boot/
	fish-guard | tee /tmp/fish.log &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping fish-guard: "
	killall fish-guard
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

